app = 'claime-agent'
primary_region = 'bom'

[build]

[http_service]
force_https = true
internal_port = 8000
min_machines_running = 1
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
