# fly.toml app configuration file for claime-agent
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'claime-agent'
primary_region = 'bom'

[build]
# Build configuration for GitHub Actions deployment
# Docker context is set in the workflow

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 8000
min_machines_running = 0
processes = ['app']

[env]
# Environment variables are passed via GitHub Actions

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
