name: Deploy to Fly.io

# DISABLED: Because apparently LangGraph thinks auth should cost extra 💸
# Requires LangGraph Enterprise license for native auth
# Could implement auth proxy but ain't nobody got time for that
# on:
#   push:
#     branches: [main]
#     paths: ["apps/agent/**"]
#   workflow_dispatch:

# Disable workflow - uncomment 'on:' section above to re-enable
# (when you feel like throwing money at LangGraph or have infinite time for auth proxies)
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    # Skip deployment when manually triggered (since workflow is disabled)
    if: false

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🪰 Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: 🚀 Deploy to Fly.io
        run: |
          flyctl deploy \
            --remote-only \
            --app claime-agent \
            --dockerfile Dockerfile \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --env OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            --env LANGSMITH_API_KEY="${{ secrets.LANGSMITH_API_KEY }}" \
            --env EXA_API_KEY="${{ secrets.EXA_API_KEY }}" \
            --env DATABASE_URI="${{ secrets.DATABASE_URI }}" \
            --env REDIS_URI="${{ secrets.REDIS_URI }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: apps/agent
